export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'solitude docs',
      description: 'Solitude is a minimalist and elegant Hexo theme designed for developers and writers.',
    },
    theme: {
      customizable: true,
      color: 'zinc',
      radius: 0.5,
    },
    header: {
      title: 'solitude-docs',
      showTitle: true,
      darkModeToggle: true,
      languageSwitcher: {
        enable: true,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      nav: [{
        title: 'Docs',
        links: [{
          title: 'Getting Started',
          to: '/getting-started/introduction',
          description: 'Learn how to set up and use the Solitude theme.',
          icon: 'lucide:rocket',
        },],
      },{
        title: 'Credits',
        links: [{
          title: 'Zhheo',
          to: 'https://blog.zhheo.com',
          description: 'Visit Zhheo\'s blog for more information.',
          icon: 'lucide:link',
          target: '_blank',
        }, {
          title: 'Hexo',
          to: 'https://hexo.io',
          description: 'Hexo is a fast, simple, and powerful blog framework.',
          icon: 'lucide:hexagon',
          target: '_blank',
        },
      ]},{
        title: 'Sponsor',
        links: [{
          title: 'Sponsor on GitHub',
          to: 'https://github.com/sponsors/everfu',
          description: 'Support the development of Solitude theme.',
          icon: 'lucide:heart',
          target: '_blank',
        },{
          title: 'Sponsor on Ko-fi',
          to: 'https://ko-fi.com/everfu',
          description: 'Buy me a coffee to support my work.',
          icon: 'lucide:coffee',
          target: '_blank',
        },{
          title: 'Sponsor on WeChat',
          to: 'https://cdn.lightxi.com/cloudreve/uploads/2025/07/03/M9VJNkNs_wechat-pay.jpg',
          description: 'Scan to support me on WeChat',
          icon: 'ri:wechat-2-line',
          target: '_blank',
          isImage: true,
        }]
      }],
      links: [{
        icon: 'ri:qq-line',
        to: 'https://qm.qq.com/q/mYIJRTqo0w',
        target: '_blank',
      },{
        icon: 'lucide:github',
        to: 'https://github.com/everfu/hexo-theme-solitude',
        target: '_blank',
      }],
    },
    aside: {
      useLevel: true,
      levelStyle: 'aside',
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      padded: true,
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: false,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: true,
        pattern: 'https://github.com/everfu/solitude.js.org/edit/main/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      credits: 'FOOTER_CREDIT',
      links: [{
        icon: 'ri:qq-line',
        to: 'https://qm.qq.com/q/mYIJRTqo0w',
        target: '_blank',
      },{
        icon: 'lucide:github',
        to: 'https://github.com/everfu/hexo-theme-solitude',
        target: '_blank',
      }],
    },
    toc: {
      enable: true,
      links: [{
        title: 'Star on GitHub',
        icon: 'lucide:star',
        to: 'https://github.com/everfu/hexo-theme-solitude',
        target: '_blank',
      }, {
        title: 'Create Issues',
        icon: 'lucide:circle-dot',
        to: 'https://github.com/everfu/hexo-theme-solitude/issues',
        target: '_blank',
      }],
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    }
  }
});